### ISSUE TITLE
How can I use the Hit Trigger for obstacles?

### ISSUE THREAD

**Issue by taki640** [KybernetikGames/platformer#10]
Is it possible to use the hit trigger or to make a simplified version for spikes and other non animated things?

**Comment by taki640** [comment]
Ok, so after reading the documentation and studying the HitTrigger script I learned that it was actually really simple.
I did this:
```
    public PolygonCollider2D _collider2D;
    public Transform source;
    public Team team;
    public int damage;

    private void OnTriggerEnter2D(Collider2D collider)
    {
        var hit = new Hit(source, team, damage);
        hit.TryHitComponent(collider);
    }
``` 
It's the way it was supposed to work?

**Comment by KybernetikGames** [comment]
Yeah, that should be pretty much all you need.

The `_collider2D` field is unnecessary though.

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available and includes spikes.
![spikes](https://user-images.githubusercontent.com/43698611/230754815-a5b2dece-d39c-4be6-aa47-a49a3b509c88.gif)
