### ISSUE TITLE
I have a issue when using texture packer

### ISSUE THREAD

**Issue by linhdo-dql** [KybernetikGames/platformer#11]
![issue](https://github.com/KybernetikGames/platformer/assets/76390603/796c7cf4-295c-498b-9886-53ad663aaa67)
Help me, please!

**Comment by KybernetikGames** [comment]
Can you please send the textures you're trying to pack (as well as their metadata files) to mail@kybernetik.com.au so I can look into the issue?

**Comment by KybernetikGames** [comment]
I'm closing this issue due to insufficient information. Feel free to re-open it if you can provide more details.
