### ISSUE TITLE
Hope to use the new input system

### ISSUE THREAD

**Issue by prybar3** [KybernetikGames/platformer#2]
Hope to use the new input system.
old input manager is really bad

**Comment by KybernetikGames** [comment]
This is on my To Do list for the next version.

If you want to implement itself, you would just need to make a copy of the `PlayerInputBrain` which uses the new input system. I don't know exactly what that entails since I haven't used it yet.

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available and the [Player Brain](https://kybernetik.com.au/platformer/docs/characters/brains/player/) now has support for the Input System package.
