### ISSUE TITLE
How to Add Knockback and Attack Offset?

### ISSUE THREAD

**Issue by prybar3** [KybernetikGames/platformer#3]
How to Add Knockback Force and
 Attack animation with Offset

**Comment by KybernetikGames** [comment]
This is also on my To Do list for the next version.

Implementing it would involve quite a few changes:

- Add a `Vector2 direction` and `float force` in `Hit.Data.cs`.
- Then you would need to add fields for those values everywhere that feeds into `Hit`:
  - `HitData` and `HitTrigger` for melee attacks.
  - `ProjectileAttackTransition` and `Projectile` for ranged attacks.
- Then the `Health` component's `ReceiveHit` method needs to apply the force to the character's rigidbody.

**Comment by prybar3** [comment]
Looking forward to the next version.
There is also ...... how to move a small distance within a specific time of the attack. Or allow me to control Rigidbody velocity when attacking

**Comment by KybernetikGames** [comment]
You could have `AdvancedAttackState` override the `MovementSpeedMultiplier` property to use a field like the [Flinch State](https://kybernetik.com.au/platformer/docs/characters/states/flinch/#movement) does, but instead of making it a serialized field, you make a public method to set it so that you can control it with [Animancer Events](https://kybernetik.com.au/animancer/docs/manual/events/animancer/).

**Comment by prybar3** [comment]
Thanks a Ton.👍

**Comment by prybar3** [comment]
> You could have `AdvancedAttackState` override the `MovementSpeedMultiplier` property to use a field like the [Flinch State](https://kybernetik.com.au/platformer/docs/characters/states/flinch/#movement) does, but instead of making it a serialized field, you make a public method to set it so that you can control it with [Animancer Events](https://kybernetik.com.au/animancer/docs/manual/events/animancer/).

This requires pressing the move button to be effective, is there any way to take effect without pressing the arrow keys

**Comment by KybernetikGames** [comment]
The official [Character Animation](https://learn.unity.com/tutorial/character-animation#5c7f8528edbc2a002053b4fb) tutorial has a section which explains Root Motion and how to add it to animations. You'd just use the [Redirecting Root Motion](https://kybernetik.com.au/animancer/docs/examples/locomotion/root-motion/#redirecting-root-motion) technique to apply it to the character's Rigidbody and also flip its x value when the sprite is flipped.

**Comment by prybar3** [comment]
[Kybernetik Edit: moved this to Issue #4.](https://github.com/KybernetikGames/platformer/issues/4)

**Comment by KybernetikGames** [comment]
[I created a separate issue since it's not related to this thread.](https://github.com/KybernetikGames/platformer/issues/4)

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available and includes knockback force on attacks.
