### ISSUE TITLE
NullReferenceException during AttackTransition event

### ISSUE THREAD

**Issue by KybernetikGames** [KybernetikGames/platformer#4]
I added a method to AdvancedAttackState to call the animation event, 
![image](https://user-images.githubusercontent.com/26576764/127866235-406ed858-9be2-4583-8d27-5ae63efe85d3.png)
![image](https://user-images.githubusercontent.com/26576764/127866330-cba9297b-5bf2-4aa1-b6fa-4d481f290765.png)

and an error occurred after several consecutive attacks
![image](https://user-images.githubusercontent.com/26576764/127866096-d4448bd1-ca30-43aa-b212-cf05a680d006.png)

_Originally posted by @prybar3 in https://github.com/KybernetikGames/platformer/issues/3#issuecomment-891005828_

**Comment by KybernetikGames** [comment]
That immediate error can be fixed by changing the first line of `RemoveHitBox` to:

```
if (_ActiveHits != null && _ActiveHits.TryGetValue(data, out var trigger))
```

But I'm not sure how it could have gotten to that point. I'll look into it a bit more.

**Comment by prybar3** [comment]
> 通过将第一行更改`RemoveHitBox`为：
> 
> ```
> if (_ActiveHits != null && _ActiveHits.TryGetValue(data, out var trigger))
> ```
> 
> 但我不确定它是如何做到这一点的。我会再研究一下。

This resulted in a new error
![image](https://user-images.githubusercontent.com/26576764/127868671-a4b529c1-712d-49c0-a331-16f3f870d8bd.png)

**Comment by KybernetikGames** [comment]
I'm not sure how that could happen since each `HitData` should only activate itself once.

Can you make a minimal reproduction project and send it to mail@kybernetik.com.au so I can take a look at it?

**Comment by prybar3** [comment]
Ok i have sent

**Comment by KybernetikGames** [comment]
Looks like it was caused by a bug in the Animancer Event system. It needs 3 changes in `AnimancerState.EventDispatcher.cs`:

- Line 53 in the `Events` property after it sets `_EventDispatcher.Events = value;` add a call to `_EventDispatcher.OnTimeChanged();`.
- Line 163 in the `Release` method after it sets `Events = null;` make it also set `_NextEventIndex = RecalculateEventIndex;`.
- Line 305 at the end of the `Update` method change `_PreviousTime = currentTime;` to `if (_NextEventIndex != RecalculateEventIndex) _PreviousTime = currentTime;`.

I'm currently working on a couple of other minor bugs and when I'm done with them I'll submit an update to the Asset Store (likely sometime in the next few days).

**Comment by KybernetikGames** [comment]
[Platformer Game Kit v1.1](https://kybernetik.com.au/platformer/docs/changes/) is now available with this fixed.
