### ISSUE TITLE
When my attack hits, can I get hit information in the attack state?

### ISSUE THREAD

**Issue by prybar3** [KybernetikGames/platformer#5]
When my attack hits, can I get hit information in the attack state? I want to switch my state after hitting an enemy. (For example, to switch to the bounce off animation after hitting a shield)

**Comment by KybernetikGames** [comment]
`CharacterAnimancerComponent.GetCurrent` is probably what you want.

**Comment by prybar3** [comment]
Hi!
it's me again!
Not being able to use code to control the character's movement at will leads to a lot of limitations. (Although RootMotion can be used for displacement, he has a lot of limitations and no code flexibility, I don't like it) 
Is it possible to have the role controller provide a SetVelocity function for external calls.

**Comment by KybernetikGames** [comment]
Give the `Character` component a reference to their `CharacterMovement` component. Then when you want a state to take control, disable the `Character.Movement` and set the `Character.Body.Velocity` directly then re-enable the `Character.Movement` afterwards.

Also, if you keep track of any modifications you make to the system and let me know, I might consider adding them to the next version if they aren't too specific to your particular game.

**Comment by prybar3** [comment]
Thank
You saved me once again
