### ISSUE TITLE
Request to add rotation flip or scale flip

### ISSUE THREAD

**Issue by prybar3** [KybernetikGames/platformer#6]
# Use Case

These flips can be handy for adding my own detection boxes or following physical hair...etc...

# Solution

rotation y = 180 flip or scale.z = -1flip

**Comment by KybernetikGames** [comment]
Horizontal flipping is currently handled in the `CharacterAnimancerComponent`, but I'm not really sure what you're asking for here. Nothing would stop you from changing the sprite's rotation and altering the Z scale would do nothing on a sprite.

**Comment by prybar3** [comment]
My bad ......
I thought this would affect the location of the hit trigger.
Please ignore this request

**Comment by KybernetikGames** [comment]
The `HitTrigger` class horizontally flips the points its given when activated if necessary and it does follow the position and rotation of the object with the `SpriteRenderer` so rotating it would move the hit area accordingly.
