### ISSUE TITLE
How can I manage different types of characters in the BehaviourTree?

### ISSUE THREAD

**Issue by acornellier** [KybernetikGames/platformer#7]
Right now, every node expects to have a `Character` passed in through context. But what if I want to have another kind of `Character` for enemies, that for example chases my player. In this case, I would need to add some state to track the target that they're currently chasing. But I don't want to add this to the common `Character` class. How can I manage this?

**Comment by KybernetikGames** [comment]
Try something like this:

1. Make a script that inherits from `BehaviourTreeBrain`. Maybe call it something like `ChaserBrain`.
2. Give it a `public Character Target { get; private set; }`
3. Override its `FixedUpdate` method to use itself as the context:

```
        protected override void FixedUpdate()
        {
            using (new Context<ChaserBrain>(this))
                base.FixedUpdate();
        }
```

4. Then any behaviour nodes executed by that method will be able to access `Context<ChaserBrain>.Current.Target`.

Setting the target could be done within the `ChaserBrain`, or if you want to do it using a node you could declare that node class inside the `ChaserBrain` class so the node can access the brain's private members (specifically, so it can set the `Target`). Or just make the `Target`'s setter public.
